#!/bin/sh
# Start/stop windmesser
#
### BEGIN INIT INFO
# Provides:          windmesser
# Required-Start:    $network $remote_fs $syslog $time
# Required-Stop:     $network $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind sssd
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind sssd
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: windmesser, gathering data from sound card and one-wire temp sensor
# Description:

### END INIT INFO
# The following part always gets executed.
#echo "This part always gets executed"

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting windmesser"
    /usr/bin/sudo -u pi /usr/bin/screen -d -m /home/pi/scripts/startWindmesser.sh
    echo "windmesser is alive"
    ;;
  stop)
    echo "Stopping windmesser"
    killall 'java'
    echo "windmesser is dead"
    ;;
  *)
    echo "Usage: /etc/init.d/windmesser {start|stop}"
    exit 1
    ;;
esac

exit 0
